### ISSUE TITLE
[RFE] Update to go-fanotify v1.0.1 (includes fix for double close on an fd)

### ISSUE THREAD

**Issue by rata** [kinvolk/inspektor-gadget#294]
## Current situation

We are [using a work-around][workaround] in the the runcfanotify code for [this issue](https://github.com/s3rj1k/go-fanotify/issues/5) in go-fanotify and a proper fix was just merged upstream. A [new release](https://github.com/s3rj1k/go-fanotify/releases/tag/v1.0.1) was created with this fix too.

[workaround]: https://github.com/kinvolk/inspektor-gadget/pull/283

## Impact

This workaround, while works just fine, is fragile. We need to be careful when using go-fanotify methods, as some might internally create a reference to the same underlying fd and all the IG code using them needs to coordinate how to close that shared fd.

As this is done by go-fanotify internally, is not obvious when writing IG code and error prone.

## Ideal future situation

Update to a version containing [this already merged PR](https://github.com/s3rj1k/go-fanotify/pull/6/files), so we don't need to worry about workarounds.

A [new release](https://github.com/s3rj1k/go-fanotify/releases/tag/v1.0.1) was created with this fix.

## **Implementation options

As the underlaying fd is not shared by different go-fanotify methods anymore, we should:
 * use its Close() method
 * Close the os.File returned by its File() method

## Additional information

Probably adding back these calls to Close is enough:
 * https://github.com/kinvolk/inspektor-gadget/pull/283/files#diff-7f754a89babb97af7bc4b6c5598abf41dd858d8569af8c9960f06309358cf59bL138
 * https://github.com/kinvolk/inspektor-gadget/pull/283/files#diff-7f754a89babb97af7bc4b6c5598abf41dd858d8569af8c9960f06309358cf59bL312

**Comment by mauriciovasquezbernal** [comment]
I'm trying to fix this issue but for some reason I can't use go-fanotify v1.0.1. Updating the module with go get fails with:

```
$ go get -u "github.com/s3rj1k/go-fanotify/fanotify@v1.0.1"
go get: module github.com/s3rj1k/go-fanotify@v1.0.1 found, but does not contain package github.com/s3rj1k/go-fanotify/fanotify
```

I turns out that v1.0.1 doesn't show up in https://pkg.go.dev/github.com/s3rj1k/go-fanotify/fanotify?tab=versions and https://pkg.go.dev/github.com/s3rj1k/go-fanotify/fanotify@v1.0.1 shows "Not found", I tried the different [options](https://pkg.go.dev/about#adding-a-package) to "request" the package but it didn't work. 

Updating to a specific commit works

```
go get -u "github.com/s3rj1k/go-fanotify/fanotify@9c00a30"
````

I'll investigate a bit more, if I'm not able to find a solution I'll update to the latest commit.
