### ISSUE TITLE
[RFE] socket collector: Show fd inode number

### ISSUE THREAD

**Issue by rata** [kinvolk/inspektor-gadget#361]
## Current situation

socket collector doesn't show the fd inode number

## Impact

The inode number is useful to dig more information about the socket (connection type, like tcp/udp/unix) and where it is connected to (to search in /proc/net/tcp* /proc/net/udp* /proc/net/unix). Without the inode number, we can't dig that out

## Ideal future situation

Include the inode number and, if possible, use it to print some other info you consider relevant from the /proc/net/{udp*,tcp*,unix}

## **Implementation options

The inode number for the open fds of process PID is shown here:
```
ls -l /proc/pid/fd
lrwx------. 1 root root 64 Oct 27 13:18 12 -> 'socket:[8739504]'
```
That means that fd 12 has inode number 8739504.

@alban mentioned that BPF iterators can't be used for this, but IG will need to look into /proc: https://kubernetes.slack.com/archives/CSYL75LF6/p1635414771016400?thread_ts=1635413905.010800&cid=CSYL75LF6

**Comment by eiffel-fl** [comment]
Hi.


I opened #449 as a draft because so far I hardcoded 42 for `tcp_timewait_sock` and `tcp_request_sock`.
Indeed, I did not find in kernel source if these sock are file-backed.
Do you know if they are file-backed?
If they are not, I will handle them particularly, for example writing "NO" for their inode number.


Best regards.

**Comment by rata** [comment]
@eiffel-fl I'll answer in the PR :)
