### ISSUE TITLE
[RFE] Have an audit mode for the Seccomp Policy Advisor

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#374]
## Current situation

Our seccomp policy advisor generates a policy that causes any syscall not included in the allowed list to raise an error. If this error is raised, it's not particularly clear to the user that it was caused by the Seccomp Policy. This can be confusing and it might be very hard to figure out if something is failing due to a blocked syscall or something else.

Seccomp itself has an audit mode, which prevents the calls from failing and outputs a log message to audit.log instead. However, this is also not particularly useful in Kubernetes, as the user needs to access the audit.log of the node to get the information of which syscalls didn't match the policy.

## Impact

It's hard to validate Seccomp Policies, regardless of whether they are set to default to ERRNO or AUDIT.

## Ideal future situation

The seccomp policy advisor could have an audit mode that generates events whenever a syscall gets blocked due to the applied policy, including the information of which namespace/pod/container generated the disallowed call.

**Comment by alban** [comment]
I was looking if the tracepoint `sys_enter` could detect a syscall that is denied by a seccomp policy. It can't detect it because `trace_sys_enter` is done after `__secure_computing`, see [syscall_trace_enter](https://github.com/torvalds/linux/blob/8bb7eca972ad531c9b149c0a51ab43a417385813/kernel/entry/common.c#L59-L77).

I also confirmed this by experimenting with the seccomp gadget: when a pod with an existing `SeccompProfile` executes a forbidden syscall, this is not detected by Inspektor Gadget (the seccomp gadget uses the `sys_enter` tracepoint).

One solution for this problem is to use `SECCOMP_RET_USER_NOTIF` (Seccomp Notify) instead of `SECCOMP_RET_ERRNO` for blocked syscalls. We would use a seccomp agent such as https://github.com/kinvolk/seccompagent to handle the notifications. But it would require runc 1.1 (still unreleased) along with other dependencies.

cc @rata

**Comment by rata** [comment]
@alban that is a nice idea! However, we need the seccomp agent to be more robust for real users to do that in production. Right now the seccomp agent is nice, but if it crashes for some reason then all the running pods in the node can't issue syscalls and such. The only way out is to restart _all_ the containers in the node if the seccomp agent crashes today.

I think, though, that improving the seccomp agent is the way to go. The more the seccomp agent handles, the more flexibility we have (it is a user-space program, after all). Of course, we shouldn't forget about the kernel limitation on what is safe to do there.

However, in the mean time, if a failed syscall can generate an entry in the audit.log of the host and some IG pod pick those up to easily show them to the user (grouped by pod/container will be great!), that seems more robust to me.

What do you think?

**Comment by marga-kinvolk** [comment]
What about using ` SECCOMP_RET_TRACE` ? https://www.kernel.org/doc/html/latest/userspace-api/seccomp_filter.html#return-values

We would still need to have the tracing filter that does the work, but maybe this is something that wouldn't depend on an unreleased runc version?

**Comment by alban** [comment]
I think both options (Seccomp's audit mode `SECCOMP_RET_LOG` and Seccomp Notify `SECCOMP_RET_USER_NOTIF`) are worth exploring.
* If it is just for an audit mode in the Seccomp Policy Advisor gadget to help users improving SeccompProfiles, then `SECCOMP_RET_LOG` could be enough and more compatible with older distros, even if parsing audit.log is not ideal.
* For more advanced use cases, `SECCOMP_RET_USER_NOTIF` would be preferable: we could then synchronously react to a blocked syscall by freezing a container for forensics, or get the Golang stack that triggered the blocked syscall via `http://localhost/debug/pprof/goroutine?debug=2` if it is a Golang program with pprof enabled, etc. If the Seccomp Agent is only used for blocked syscalls, then its reliability is not such a big problem because it would only impact processes that try to call forbidden syscalls (by returning ENOSYS).

**Comment by rata** [comment]
@alban oh, right, it will only be blocked syscalls, so it should not be that bad if the seccomp agent crashes. Cool, +1 :)

**Comment by alban** [comment]
About audit.log:

Seccomp can log a syscall either if the seccomp program returns `SCMP_ACT_LOG` or if the `seccomp()` syscall was done with `SECCOMP_FILTER_FLAG_LOG`, configurable with the global sysctl `/proc/sys/kernel/seccomp/actions_logged`. Either way, audit does not gives any way to distinguish the container: there is no namespace or cgroup information. The process might be gone by the time we read `/proc/$pid`. Example of audit log in `/var/log/audit/audit.log`:

```
type=SECCOMP msg=audit(1635936929.358:12242): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=kernel pid=1752754 comm="mkdir" exe="/bin/mkdir" sig=0 arch=c000003e syscall=83 compat=0 ip=0x4ba511 code=0x7ffc0000^]AUID="unset" UID="root" GID="root" ARCH=x86_64 SYSCALL=mkdir
```

There are some discussions to make it container-aware but it is not done:
https://lwn.net/Articles/699819/

**Comment by alban** [comment]
IG could add a kprobe on [audit_seccomp](https://github.com/torvalds/linux/blob/dcd68326d29b62f3039e4f4d23d3e38f24d37360/kernel/auditsc.c#L2949) (called for `SCMP_ACT_LOG`) and then `current->nsproxy->mnt_ns->ns.inum` to identify the container.
