### ISSUE TITLE
tcpconnect: The header line is printed multiple times

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#419]
## Description

The header line is printed multiple times when running tcpconnect gadget. 

Reproduced only when deploying the IG with the option `--tools-mode=standard`.

## Impact

It does not look good and impact the UX.

## Environment and steps to reproduce

1. **Set-up**: Reproduced in kubeadm and AKS underlay clusters.
2. **Task**: Run tcpconnect gadget
3. **Action(s)**:
  a. Deploy IG with `--tools-mode=standard`
  b. Run tcpconnect
4. **Error**: 
    ```
    $ ./kubectl-gadget tcpconnect -A
    Tracing connect ... Hit Ctrl-C to end
    NODE             NAMESPACE        POD              CONTAINER        PID    COMM         IP SADDR            DADDR            DPORT
    NODE             NAMESPACE        POD              CONTAINER        PID    COMM         IP SADDR            DADDR            DPORT
    aks-agentpool-41917616-vmss000001 kube-system      omsagent-rfzh8   omsagent         8940   event_loop   4  10.244.0.2       10.0.161.255     25227
    NODE             NAMESPACE        POD              CONTAINER        PID    COMM         IP SADDR            DADDR            DPORT
    aks-agentpool-41917616-vmss000001 kube-system      coredns-845757d86-77xxc coredns          6999   coredns      4  127.0.0.1        127.0.0.1        8080
    aks-agentpool-41917616-vmss000001 calico-system    calico-node-zvhtd calico-node      5354   calico-node  4  127.0.0.1        127.0.0.1        9099
    ```

## Expected behavior

The header line is printed only once.

**Comment by eiffel-fl** [comment]
Hi.

This bug is sadly tricker than I expected, adding this simple patch:

```patch
diff --git a/gadget-container/gadgets/bcck8s/bcc-wrapper.sh b/gadget-container/gadgets/bcck8s/bcc-wrapper.sh
index 1a9cfda..bcc999c 100755
--- a/gadget-container/gadgets/bcck8s/bcc-wrapper.sh
+++ b/gadget-container/gadgets/bcck8s/bcc-wrapper.sh
@@ -136,6 +136,7 @@ if [ "$MANAGER" = "true" ] ; then
     MODE="--cgroupmap"
     MAPPATH=$BPFDIR/gadget/cgroupidset_$TRACERID
   fi
+  echo "Bug ($(hostname))"
   exec $GADGET $MODE $MAPPATH "$@"
 else
   exec $GADGET "$@"
```

Leads all the gadget to print their header several times (in my case two since I have two nodes):

```bash
$ ./kubectl-gadget mountsnoop -n test-ns
Bug (aks-nodepool1-20876740-vmss000001)
NODE             NAMESPACE        POD              CONTAINER        COMM             PID     TID     MNT_NS      CALL
NODE             NAMESPACE        POD              CONTAINER        COMM             PID     TID     MNT_NS      CALL
```

This leads me to suspect there is a race condition underneath but I am not sure where and how to solve it...


Best regards.

**Comment by mauriciovasquezbernal** [comment]
> For strange reasons, the first outputted line is not printed.

This is by design. We only print the first line coming from the different nodes once, otherwise the header will be printed multiple times: https://github.com/kinvolk/inspektor-gadget/blob/7925af2181cb6788e2cccfdc998868b080a856ec/cmd/kubectl-gadget/utils/post-process.go#L44

> In fact, all the gadgets which print something before the header (like "Hit Ctrl-C to end") are affected:

Yes, we're only skipping the first line (that's why `Hit Ctrl-C...` line is printed only once in those cases). 

I tried to find a way to skip more than one line but it's not that easy to implement without having corner cases where this logic could fail. IMO the effort to fix this issue now is not worth it.

**Comment by eiffel-fl** [comment]
Oh sorry, I missed this option.

A "solution" would be to remove bcc printing "Hit Ctrl-C..." and to skip $n - 1$ first lines (n being the number of nodes).
But I agree with you this is not really worth it.
