### ISSUE TITLE
fsslower: It is not working on OpenShift (ARO)

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#571]
## Description

Fsslower gadget neither generates an output nor report an error when running in [Azure Red Hat OpenShift (ARO) cluster](https://docs.microsoft.com/en-us/azure/openshift/intro-openshift).

## Environment and steps to reproduce

Once https://github.com/kinvolk/inspektor-gadget/pull/561 is merged, it will be enough to go to the [integration/integration_test.go](https://github.com/kinvolk/inspektor-gadget/blob/main/integration/integration_test.go) and avoid `TestFsslower` test is skipped for ARO (Azure RedHat OpenShift) distribution.

**Comment by mauriciovasquezbernal** [comment]
How did you notice this problem, by testing manually or by running the integration tests? 

It seems the problem is that the integration test is using `ext4` as the filesystem but ARO uses `xfs`:

 `./kubectl-gadget fsslower --type xfs -m 0` procudes a lot of events, while `./kubectl-gadget fsslower --type ext4 -m 0` doesn't produce any.

**Comment by blanquicet** [comment]
I tested it with the integration tests and it is always using `ext4`. I updated them in https://github.com/kinvolk/inspektor-gadget/pull/561 to use `xfs` for ARO and they are passing now. Thanks!
