### ISSUE TITLE
[RFE] Allow directly running gadgets with local-gadget

### ISSUE THREAD

**Issue by margamanterola** [kinvolk/inspektor-gadget#638]
## Current situation

Currently local-gadget requires a lot of steps in order to run a gadget. This is good for developing and testing, but not particularly user-friendly.

## Impact

It's not possible to just run a command and get the output of a gadget, the user needs to enter a series of not very intuitive inputs in order to get the gadget output

## Ideal future situation

`local-gadget` should be able to directly run gadgets with the same syntax as `kubectl-gadget` does, while still having the interactive mode be a debugging/testing option.

**Comment by blanquicet** [comment]
The first effort for this issue: https://github.com/kinvolk/inspektor-gadget/pull/730

**Comment by blanquicet** [comment]
After the reorganization of the issue [#642](https://github.com/kinvolk/inspektor-gadget/issues/642), this task is now in charge of moving the re-factorized code into a common package and then using it from `local-gadget`.

Given that reorganization, these are the missing tasks to complete this issue:

  - [ ] Requirement:  [#642](https://github.com/kinvolk/inspektor-gadget/issues/642)
  - [ ] `snapshot` category: 
    - [ ] process: [#730](https://github.com/kinvolk/inspektor-gadget/pull/730)
    - [ ] socket: The CLI code is ready but it wasn't enabled because without k8s metadata, the output is not clear enough. See [#744](https://github.com/kinvolk/inspektor-gadget/issues/744).
  - [ ] `trace` category: TODO
  - [ ] `profile` category: TODO
  - [ ] `advise` category: TODO (Only applicable for seccomp-profile because network-policy doesn't make sense for `local-gadget`.
  - [ ] `audit` category: TODO
  - [ ] `top` category: We decided not to work yet on this category because we are discussing a possible change for the GlobalTracer/API which may change the implementation of the CLI for those gadgets: [#673](https://github.com/kinvolk/inspektor-gadget/issues/673)

**Comment by blanquicet** [comment]
Replaced by https://github.com/kinvolk/inspektor-gadget/issues/861
