### ISSUE TITLE
[RFE] local-gadget: Create integration tests

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#738]
## Current situation

There are no integration-tests for the `local-gadget`. Once we agree on how to implement the single call run https://github.com/kinvolk/inspektor-gadget/pull/730, we should start implementing the tests for them.  

As said in https://github.com/kinvolk/inspektor-gadget/issues/719, these tests should test the JSON format and the transformation from JSON to columns will be done by unit-testing the GadgetParsers' method, e.g. for [the socket gadget](https://github.com/kinvolk/inspektor-gadget/blob/65a398e8ef72887c9b36550de64e7b00cfa8451f/cmd/kubectl-gadget/snapshot/socket.go#L33-L38).

**Comment by alban** [comment]
There are no integration tests, but there are tests for various gadgets in local-gadget with docker containers:
```
make local-gadget-tests
```
I wonder how to avoid test duplication. I think the tests in `make local-gadget-tests` should be kept because they run fast during development of new gadgets. Integration tests will be slower.
